# fly.toml app configuration file generated for misty-silence-6581 on 2023-08-01T10:45:33+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "misty-silence-6581"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
